spring:
  application:
    name: letscode-by-ada
  profiles: default, local, develop
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: ${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

security:
  oauth2:
    client:
      scope: password
  jwt:
    signing-key: Y2FiZcOnYSBkYSBvbsOnYQ==