spring:
  application:
    name: letscode-by-ada
  profiles: default, local, develop
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: "jdbc:mysql://doadmin:AVNS_oVszXJLpbhPDHEanhq8@db-mysql-nyc1-banco-do-user-12782142-0.b.db.ondigitalocean.com:25060/defaultdb?ssl-mode=REQUIRED"
    username: "doadmin"
    password: "AVNS_oVszXJLpbhPDHEanhq8"

security:
  oauth2:
    client:
      scope: password
  jwt:
    signing-key: Y2FiZcOnYSBkYSBvbsOnYQ==