apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendjava
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backendjava
  template:
    metadata:
      labels:
        app: backendjava
    spec:
      containers:
      - name: backendjava
        image: dverazs/springbootprof:latest
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: MYSQL_DB_HOST
          value: "jdbc:mysql://doadmin:AVNS_oVszXJLpbhPDHEanhq8@db-mysql-nyc1-banco-do-user-12782142-0.b.db.ondigitalocean.com:25060/defaultdb?ssl-mode=REQUIRED"
        - name: MYSQL_DB_USER
          value: "doadmin"
        - name: MYSQL_DB_PASS
          value: "AVNS_oVszXJLpbhPDHEanhq8"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: backendjava-service
spec:
  selector:
    app: backendjava
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  #type: NodePort
  #type: LoadBalancer
