apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendjava
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backendjava
  template:
    metadata:
      labels:
        app: backendjava
    spec:
      containers:
      - name: backendjava
        image: dverazs/springbootprof:latest
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: backendjava-service
spec:
  selector:
    app: backendjava
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  #type: NodePort
  #type: LoadBalancer
