#
# Build stage
#
FROM maven:3.8.6-jdk-11-slim AS build
COPY src /usr/src/app/src  
COPY pom.xml /usr/src/app

RUN mvn -f /usr/src/app/pom.xml clean package

#
# Package stage
#
FROM gcr.io/distroless/java  
COPY --from=build /usr/src/app/target/letscodebyada-0.0.1-SNAPSHOT.jar /usr/app/letscodebyada-0.0.1-SNAPSHOT.jar  
EXPOSE 8080
ENTRYPOINT ["java","-jar","/usr/app/letscodebyada-0.0.1-SNAPSHOT.jar"]  
